language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install .
  - pip install coveralls
script: nosetests --with-coverage --cover-package=pathhistogram
after_success:
  - coveralls
